#!/usr/bin/python

# read a boxile generated by EMAN/e2boxer.py return a list of [x,y] for each coordinate, corrected for the xy shifts
# tested on boxfiles written by e2boxer.py on a MRC file
#   - columns separated by tabs
#   - image xy origin = lower left corner
#   - coordinates = box upper left corner, dependent on box size

# returns a list in format:
# [(x,y),(x,y)]
# for all coords, in order
# box origin now coordinate center, image origin is still lower left corner

#----FUNCTION: read boxfile and output box size corrected list ---#

import sys



def readboxfile(file):
    if '-r' in sys.argv[1:]:
        roundmode = True
        print "** Rounding to nearest whole number **"

    else:
        roundmode = False
        
    
    rawdata = open(file,'r').readlines()
    newcoords = []
    for i in rawdata:
        line = i.strip('\n').split('\t')
        assert line[2] == line[3], 'ERROR: non-square box'
        x = float(line[0]) + 0.5*float(i[2])
        y = float(line[1]) + 0.5*float(i[2])
        if roundmode == True:
            newcoords.append((int(round(x)),int(round(y))))
        else:
            newcoords.append((x,y))
    return newcoords    




print readboxfile("test.box")
